"""Initial schema

Revision ID: 4c191330a96c
Revises: 
Create Date: 2025-12-21 09:26:19.080787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c191330a96c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.Enum('request_created', 'request_sent', 'response_received', 'response_scanned', 'email_scanned', 'broker_detected', 'error', 'warning', 'info', name='activitytype'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('broker_id', sa.Uuid(), nullable=True),
    sa.Column('deletion_request_id', sa.Uuid(), nullable=True),
    sa.Column('response_id', sa.Uuid(), nullable=True),
    sa.Column('email_scan_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_activity_type'), 'activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_broker_id'), 'activity_logs', ['broker_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_deletion_request_id'), 'activity_logs', ['deletion_request_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_email_scan_id'), 'activity_logs', ['email_scan_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_response_id'), 'activity_logs', ['response_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('data_brokers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('privacy_email', sa.String(), nullable=True),
    sa.Column('opt_out_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_brokers_name'), 'data_brokers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('deletion_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('broker_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'CONFIRMED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('generated_email_subject', sa.String(), nullable=True),
    sa.Column('generated_email_body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('gmail_sent_message_id', sa.String(), nullable=True),
    sa.Column('gmail_thread_id', sa.String(), nullable=True),
    sa.Column('last_send_error', sa.Text(), nullable=True),
    sa.Column('send_attempts', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['data_brokers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_requests_broker_id'), 'deletion_requests', ['broker_id'], unique=False)
    op.create_index(op.f('ix_deletion_requests_gmail_sent_message_id'), 'deletion_requests', ['gmail_sent_message_id'], unique=False)
    op.create_index(op.f('ix_deletion_requests_gmail_thread_id'), 'deletion_requests', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_deletion_requests_user_id'), 'deletion_requests', ['user_id'], unique=False)
    op.create_table('email_scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('broker_id', sa.Uuid(), nullable=True),
    sa.Column('gmail_message_id', sa.String(), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('sender_domain', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('is_broker_email', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('classification_notes', sa.Text(), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['data_brokers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_scans_broker_id'), 'email_scans', ['broker_id'], unique=False)
    op.create_index(op.f('ix_email_scans_gmail_message_id'), 'email_scans', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_email_scans_sender_domain'), 'email_scans', ['sender_domain'], unique=False)
    op.create_index(op.f('ix_email_scans_user_id'), 'email_scans', ['user_id'], unique=False)
    op.create_table('broker_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('deletion_request_id', sa.Uuid(), nullable=True),
    sa.Column('gmail_message_id', sa.String(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('response_type', sa.Enum('confirmation', 'rejection', 'acknowledgment', 'request_info', 'unknown', name='responsetype'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('matched_by', sa.String(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deletion_request_id'], ['deletion_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_responses_deletion_request_id'), 'broker_responses', ['deletion_request_id'], unique=False)
    op.create_index(op.f('ix_broker_responses_gmail_message_id'), 'broker_responses', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_broker_responses_gmail_thread_id'), 'broker_responses', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_broker_responses_user_id'), 'broker_responses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_responses_user_id'), table_name='broker_responses')
    op.drop_index(op.f('ix_broker_responses_gmail_thread_id'), table_name='broker_responses')
    op.drop_index(op.f('ix_broker_responses_gmail_message_id'), table_name='broker_responses')
    op.drop_index(op.f('ix_broker_responses_deletion_request_id'), table_name='broker_responses')
    op.drop_table('broker_responses')
    op.drop_index(op.f('ix_email_scans_user_id'), table_name='email_scans')
    op.drop_index(op.f('ix_email_scans_sender_domain'), table_name='email_scans')
    op.drop_index(op.f('ix_email_scans_gmail_message_id'), table_name='email_scans')
    op.drop_index(op.f('ix_email_scans_broker_id'), table_name='email_scans')
    op.drop_table('email_scans')
    op.drop_index(op.f('ix_deletion_requests_user_id'), table_name='deletion_requests')
    op.drop_index(op.f('ix_deletion_requests_gmail_thread_id'), table_name='deletion_requests')
    op.drop_index(op.f('ix_deletion_requests_gmail_sent_message_id'), table_name='deletion_requests')
    op.drop_index(op.f('ix_deletion_requests_broker_id'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_data_brokers_name'), table_name='data_brokers')
    op.drop_table('data_brokers')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_response_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_email_scan_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_deletion_request_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_broker_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
